/** Full ChatView child conversation + Agent loadout UI. Isolated Electron, no user data. */
const { _electron: electron } = require('playwright-core')
const fs = require('fs')
const os = require('os')
const path = require('path')
const assert = require('assert/strict')
const { startStubEngine } = require('./lib/stub-engine.cjs')
const ROOT = path.join(__dirname, '..')
const home = fs.mkdtempSync(path.join(os.tmpdir(), 'forsion-agent-profile-'))
const base = { archived: false, model_id: 'm1', created_at: '2026-09-16 10:00:00', updated_at: '2026-09-16 10:00:00', projectless: false, project_path: home, project_name: 'Atlas' }
const config = { groupChat: true, groupAgents: ['xyra', 'research'], execMode: 'host', cwd: home, agentSlug: 'xyra' }
const main = { ...base, id: 'profile-main', title: 'Atlas team', agent_config: config }
const child = { ...base, id: 'profile-child', title: 'Research work', agent_config: { agentSlug: 'research', execMode: 'host', cwd: home, teamMember: { teamSessionId: main.id } } }
const agents = ['xyra', 'research'].map((slug) => ({ slug, name: slug === 'xyra' ? 'Xyra' : 'Research', description: slug === 'xyra' ? 'Project coordination' : 'Evidence and analysis', tools: [], model: '', thinkingLevel: '', maxIterations: null, approvalMode: '', systemPrompt: 'Be precise.', soul: '', createdBy: 'user', libraryDir: path.join(home, slug, 'Library') }))
const text = 'Full child conversation detail. '.repeat(60) + 'END-OF-COMPLETE-REPORT'
const toolResult = 'Complete tool output '.repeat(100) + 'END-OF-TOOL-RESULT'
const childMessages = [{ id: 'child-user', session_id: child.id, role: 'user', content: 'Research this thoroughly', timestamp: 1 }, { id: 'child-answer', session_id: child.id, role: 'model', content: text, reasoning: 'A detailed reasoning record.', agent_slug: 'research', timestamp: 2, tool_calls: [{ id: 'read-1', type: 'function', function: { name: 'read_file', arguments: '{"path":"evidence.md"}' } }], tool_results: [{ tool_call_id: 'read-1', content: toolResult, isError: false }] }]
const solo = { ...base, id: 'profile-solo', title: 'Research notes', agent_config: { agentSlug: 'research', execMode: 'host', cwd: home } }
let saved = null, sessionModelSaved = null, avatarWrites = 0, avatarDeletes = 0
let app
async function run() {
  const stub = await startStubEngine({ agents, sessions: [main, solo], messages: [{ id: 'main-user', role: 'user', content: 'Plan the research', timestamp: 1 }, { id: 'main-answer', role: 'model', content: 'The team is ready.', timestamp: 2 }], override: async ({ path: p, method, body }) => {
    if (p === `/agent/sessions/${solo.id}` && method === 'PATCH') { const patch = await body(); sessionModelSaved = patch.model_id; Object.assign(solo, patch); return { session: solo } }
    if (p.endsWith('/memory/dream')) return { config: { enabled: false, modelId: '', timeoutMs: 60000, maxOutputTokens: 4096, intervalHours: 6 }, status: { state: 'idle', running: false }, candidates: 0 }
    if (p.endsWith('/memory/revisions')) return { revisions: [] }
    if (p.endsWith('/memory') && method === 'GET') return { version: 'version-1', content: 'Cite primary sources.', entries: [{ id: 'memory-1', content: 'Cite primary sources.', source: { kind: 'manual' }, evidenceIds: [], createdAt: 1, updatedAt: 1 }], tombstones: [], updatedAt: 1 }
    if (p === '/agent/runs' && method === 'GET') return { runs: [] }
    if (p.endsWith('/detail')) return { session: child }
    if (p.endsWith('/background')) return { background: [{ sessionId: child.id, kind: 'teamwork', title: child.title, agentSlug: 'research', runId: null, runStatus: null }] }
    if (p === `/agent/sessions/${child.id}/messages`) return { messages: childMessages }
    if (p.endsWith('/config') && p.startsWith('/agent/sessions/')) return { agent_config: p.includes(child.id) ? child.agent_config : p.includes(solo.id) ? solo.agent_config : config }
    if (p === '/agent/skills') return { skills: [{ id: 'local:research', name: 'Research notebook', description: 'Gather and cite evidence' }, { id: 'local:writing', name: 'Writing', description: 'Write clear reports' }] }
    if (p === '/agent/tools') return { builtins: [], custom: [], mcp: [{ server: 'documents', status: 'connected', transport: 'stdio', tools: [{ name: 'read', description: 'Read documents' }] }] }
    if (p === '/agent/agents/research/avatar' && method === 'POST') { avatarWrites++; agents.find((a) => a.slug === 'research').avatar = 'avatar.png'; return { ok: true, avatar: 'avatar.png' } }
    if (p === '/agent/agents/research/avatar' && method === 'DELETE') { avatarDeletes++; delete agents.find((a) => a.slug === 'research').avatar; return { ok: true } }
    if (p.startsWith('/agent/agents/') && method === 'PATCH') { saved = await body(); const slug = p.split('/')[3]; const i = agents.findIndex((a) => a.slug === slug); agents[i] = { ...agents[i], ...saved }; return { agent: agents[i] } }
  } })
  try {
    const ud = path.join(home, 'userData')
    for (const dir of [ud, `${ud}-dev`]) {
      fs.mkdirSync(dir, { recursive: true })
      fs.writeFileSync(path.join(dir, 'tangu-desktop-config.json'), JSON.stringify({ mode: 'external', backendUrl: stub.url, token: 'e2e' }))
    }
    app = await electron.launch({ args: [`--user-data-dir=${ud}`, '--lang=zh-CN', ROOT], cwd: ROOT, env: { ...process.env, TANGU_HOME: home, TANGU_BACKEND_URL: stub.url } })
    const win = await app.firstWindow()
    const errors = []
    win.on('pageerror', (e) => errors.push(String(e)))
    win.setDefaultTimeout(15000)
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1500, 1000))
    await win.waitForSelector('#root')
    await win.waitForTimeout(2000)
    for (const label of ['跳过引导', 'Skip']) { const b = win.getByText(label, { exact: true }); if (await b.count()) { await b.first().click(); break } }
    await win.waitForSelector('.dv-groupview')
    await win.evaluate(() => localStorage.setItem('forsion_default_space', 'tangu'))
    await win.reload()
    assert.equal(await win.getByTitle('Tangu', { exact: true }).count() > 0, true, 'Tangu Space must not collide with the Agents label')
    await win.locator('.t2s-srow, .t2o-row').filter({ hasText: 'Atlas team' }).first().click()
    await win.locator('[data-team-desk="status"] [data-slug="research"]').click()
    const panel = win.locator('.child-chat-panel')
    await panel.locator('[data-chat-surface="child-chat"]').waitFor()
    assert.equal(await panel.getByText(/END-OF-COMPLETE-REPORT/).count(), 1)
    assert.equal(await win.locator('.t2-tsum [data-team-desk="work"]').count(), 0)
    assert.equal(await win.locator('[data-chat-surface="chat"]').getAttribute('data-session-id'), main.id)
    await panel.locator('.t2c-ta').fill('Continue with sources')
    await panel.locator('.t2c-ta').press('Enter')
    await win.waitForTimeout(500)
    assert.equal(stub.seen.runs.at(-1)?.sessionId, child.id)
    assert.equal(stub.seen.runs.at(-1)?.agentConfig.agentSlug, 'research')
    assert.equal(stub.seen.runs.at(-1)?.agentConfig.teamMember.teamSessionId, main.id)
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'child-chat.png') })
    console.log('PASS child full history, isolated send and retained parent identity')
    await panel.locator('.agent-desk-head button').click()
    await win.locator('.dv-edge-right').click()
    await win.locator('[data-tangu-details]').waitFor()
    assert.equal(await win.locator('[data-tangu-details]').getByText('团队', { exact: true }).count(), 1)
    await win.locator('.t2s-srow, .t2o-row').filter({ hasText: 'Research notes' }).first().click()
    await win.locator('[data-tangu-details] [data-agent-profile="research"]').waitFor()
    assert.equal(await win.locator('.dv-tab[title="子聊天"], .dv-tab[title="记忆"], .dv-tab[title="Chat"]').count(), 0)
    const compact = win.locator('[data-tangu-details] [data-agent-profile="research"]')
    await compact.locator('.agent-current-session .profile-model-trigger').click()
    await compact.getByLabel('搜索模型或输入模型 ID', { exact: true }).press('ArrowDown')
    assert.equal(await compact.locator('.profile-model-results button').first().evaluate((el) => el === document.activeElement), true)
    await compact.locator('.profile-model-results button').first().press('Escape')
    assert.equal(await compact.locator('.agent-current-session .profile-model-trigger').evaluate((el) => el === document.activeElement), true)
    await compact.locator('.agent-current-session .profile-model-trigger').click()
    await compact.getByLabel('搜索模型或输入模型 ID', { exact: true }).fill('custom/session-model')
    await compact.getByRole('button', { name: '使用模型 ID：custom/session-model', exact: true }).click()
    await win.waitForTimeout(200)
    assert.equal(sessionModelSaved, 'custom/session-model')
    await compact.locator('.profile-config-group .profile-model-trigger').click()
    await compact.getByLabel('搜索模型或输入模型 ID', { exact: true }).fill('Stub')
    await compact.getByRole('button', { name: 'Stub m1', exact: true }).click()
    await compact.getByLabel('思考档位', { exact: true }).selectOption('high')
    await compact.getByRole('button', { name: '保存配置', exact: true }).click()
    await win.waitForTimeout(200)
    assert.equal(saved.model, 'm1')
    assert.equal(saved.thinkingLevel, 'high')
    assert.equal(solo.model_id, 'custom/session-model', 'Agent defaults must not overwrite a conversation override')
    await win.waitForTimeout(220)
    await compact.locator('.agent-profile-content').evaluate((el) => el.scrollTop = 0)
    await win.screenshot({ path: path.join(home, 'details-panel.png') })
    console.log('PASS overview model/thinking edits persist; session and Agent scopes remain independent')
    await win.locator('[data-tangu-details] .agent-section-nav button').filter({ hasText: '技能' }).click()
    await compact.getByLabel('搜索名称或描述', { exact: true }).fill('Writing')
    assert.equal(await compact.locator('.agent-equipment-item').count(), 1)
    await compact.getByLabel('Writing', { exact: false }).uncheck()
    await compact.getByLabel('搜索名称或描述', { exact: true }).fill('')
    await compact.getByRole('button', { name: '仅看已启用', exact: true }).click()
    assert.equal(await compact.locator('.agent-equipment-item').count(), 1)
    await compact.getByRole('button', { name: '仅看已启用', exact: true }).click()
    const geometry = await compact.evaluate((el) => {
      const body = el.querySelector('.agent-profile-content'), nav = el.querySelector('.agent-section-nav'), footer = el.querySelector('.agent-profile-save')
      body.scrollTop = body.scrollHeight
      return { footer: footer.getBoundingClientRect().bottom, panel: el.getBoundingClientRect().bottom, nav: nav.getBoundingClientRect().bottom, body: body.getBoundingClientRect().top, overflow: el.scrollWidth > el.clientWidth + 1 }
    })
    assert.ok(geometry.footer <= geometry.panel + 1 && geometry.nav <= geometry.body + 1 && !geometry.overflow)
    await win.locator('[data-tangu-details]').getByRole('button', { name: '保存配置', exact: true }).click()
    await win.waitForTimeout(200)
    assert.deepEqual(saved.enabledSkillIds, ['local:research'])
    console.log('PASS default right details follows main session; compact skill editing')
    await compact.getByRole('tab', { name: '记忆', exact: true }).click()
    const memory = compact.locator('[data-testid="agent-memory-panel"]')
    await memory.getByText('Cite primary sources.', { exact: true }).first().waitFor()
    await memory.getByLabel('搜索记忆', { exact: true }).fill('absent')
    await memory.getByText('没有匹配的记忆', { exact: true }).waitFor()
    await memory.getByLabel('搜索记忆', { exact: true }).fill('')
    await memory.getByRole('button', { name: '编辑原文', exact: true }).click()
    await memory.getByRole('textbox', { name: '记忆原文', exact: true }).fill('Unsaved memory draft')
    await compact.getByRole('tab', { name: '技能', exact: true }).click()
    await compact.getByRole('tab', { name: '记忆', exact: true }).click()
    assert.equal(await memory.getByRole('textbox', { name: '记忆原文', exact: true }).inputValue(), 'Unsaved memory draft')
    await win.waitForTimeout(220)
    assert.ok(!(await compact.locator('.agent-profile-save').textContent()).includes('已保存'), 'An Agent save must not imply an unsaved memory draft was saved')
    await win.screenshot({ path: path.join(home, 'memory-editor.png') })
    await compact.getByRole('tab', { name: '配置', exact: true }).click()
    // 基本信息并进头部:头像点开即换(立即保存),名称 / 简介原地编辑、与工作指令同走一个保存栏;配置页不再单列「基本信息」。
    assert.equal(await compact.getByText('基本信息', { exact: true }).count(), 0)
    const heroPortrait = compact.locator('.agent-character-hero .agent-portrait')
    await compact.getByLabel('更换头像', { exact: true }).setInputFiles({ name: 'avatar.png', mimeType: 'image/png', buffer: Buffer.from('89504e470d0a1a0a', 'hex') })
    await win.waitForTimeout(200)
    assert.equal(avatarWrites, 1)
    assert.equal(await heroPortrait.locator('img').count(), 1)
    await compact.locator('.agent-portrait-slot').hover()
    await win.waitForTimeout(220)
    await compact.locator('.agent-character-hero').screenshot({ path: path.join(home, 'hero-hover.png') })
    await compact.getByRole('button', { name: '移除头像', exact: true }).click()
    await win.waitForTimeout(200)
    assert.equal(avatarDeletes, 1)
    assert.equal(await heroPortrait.locator('img').count(), 0)
    await compact.getByLabel('名称', { exact: true }).fill('Research Lead')
    await compact.getByLabel('简介', { exact: true }).fill('Finds and checks primary evidence.')
    await win.waitForTimeout(220)
    await compact.locator('.agent-character-hero').screenshot({ path: path.join(home, 'hero-edit.png') })
    await compact.getByLabel('工作指令', { exact: true }).fill('# Instructions\n\nKeep source citations.')
    await compact.locator('.profile-text-editor').first().getByRole('button', { name: '阅读预览', exact: true }).click()
    await compact.locator('.profile-text-preview h1').getByText('Instructions', { exact: true }).waitFor()
    await compact.getByRole('button', { name: '保存配置', exact: true }).click()
    await win.waitForTimeout(200)
    assert.equal(saved.systemPrompt, '# Instructions\n\nKeep source citations.')
    assert.equal(saved.name, 'Research Lead')
    assert.equal(saved.description, 'Finds and checks primary evidence.')
    assert.equal(await compact.getByLabel('名称', { exact: true }).inputValue(), 'Research Lead')
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'instructions-preview.png') })
    await compact.getByRole('tab', { name: '配置', exact: true }).press('Home')
    assert.equal(await compact.getByRole('tab', { name: '配置', exact: true }).getAttribute('aria-selected'), 'true')
    assert.equal(await compact.getByText('能力装备', { exact: true }).count(), 0)
    // 「能力装备」整块(跳技能 / MCP / 记忆的三张卡)与上方标签重复,已并掉:配置页正文里不该再有这类跳转卡。
    // 只量当前标签的正文(.profile-section-enter):记忆面板保持挂载(hidden)也在 .agent-profile-content 里,会误数。
    assert.equal(await compact.locator('.profile-section-enter button').filter({ hasText: /^(技能|MCP|记忆)/ }).count(), 0, 'Config tab must not repeat the Skills / MCP / Memory tabs as cards')
    console.log('PASS searchable memory, retained drafts, Markdown preview and keyboard tab navigation')
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1024, 720))
    await compact.getByRole('tab', { name: '技能', exact: true }).click()
    await compact.getByRole('button', { name: '全部停用', exact: true }).click()
    const dock = await compact.evaluate((el) => {
      const footer = el.querySelector('.agent-profile-save').getBoundingClientRect()
      return { bottom: footer.bottom, viewport: innerHeight, content: el.querySelector('.agent-profile-content').clientHeight, overflow: el.scrollWidth > el.clientWidth + 1 }
    })
    assert.ok(dock.bottom <= dock.viewport && dock.content > 100 && !dock.overflow)
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'compact-skills-unsaved.png') })
    await compact.getByRole('button', { name: '放弃修改', exact: true }).click()
    await win.emulateMedia({ reducedMotion: 'reduce' })
    await compact.getByRole('tab', { name: '配置', exact: true }).click()
    assert.equal(await compact.locator('.profile-section-enter').evaluate((el) => getComputedStyle(el).animationName), 'none')
    assert.equal(await compact.locator('.agent-section-nav').evaluate((el) => getComputedStyle(el, '::before').transitionProperty), 'none')
    await win.emulateMedia({ reducedMotion: 'no-preference' })
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(1500, 1000))

    // Ribbon exposes the new Space directly.
    const agentsButton = win.locator('[data-ribbon-id="space:agents"], [data-id="space:agents"], button[title="Agents"]').first()
    if (await agentsButton.count()) await agentsButton.click()
    else await win.getByRole('button', { name: 'Agents', exact: true }).first().click()
    await win.locator('[data-agents-space]').waitFor()
    await win.locator('.agents-roster-item').filter({ hasText: 'Research' }).click()
    const profile = win.locator('[data-agent-profile="research"]')
    await profile.locator('.agent-section-nav button').filter({ hasText: '技能' }).click()
    assert.equal(await profile.getByLabel('Writing', { exact: false }).isChecked(), false)
    await profile.getByLabel('Writing', { exact: false }).check()
    await profile.getByLabel('Writing', { exact: false }).uncheck()
    await profile.getByRole('button', { name: '保存配置', exact: true }).click()
    await win.waitForTimeout(300)
    assert.deepEqual(saved.enabledSkillIds, ['local:research'])
    await profile.locator('.agent-section-nav button').filter({ hasText: 'MCP' }).click()
    await profile.getByLabel('documents', { exact: false }).uncheck()
    await profile.getByRole('button', { name: '保存配置', exact: true }).click()
    await win.waitForTimeout(300)
    assert.deepEqual(saved.enabledMcpServers, [])
    await profile.locator('.agent-section-nav button').filter({ hasText: '配置' }).click()
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'agents-light.png') })
    await win.evaluate(() => { document.documentElement.setAttribute('data-mode', 'dark'); document.documentElement.classList.add('dark') })
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'agents-dark.png') })
    await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(820, 900))
    await win.waitForTimeout(250)
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'agents-narrow.png') })
    assert.equal(await profile.evaluate((el) => el.scrollWidth > el.clientWidth + 1), false)
    await win.evaluate(() => { localStorage.setItem('tangu_locale', 'en'); localStorage.setItem('forsion_default_space', 'agents') })
    await win.reload()
    await win.locator('[data-agents-space]').waitFor()
    await win.locator('.agents-roster-item').filter({ hasText: 'Research' }).click()
    await profile.getByRole('tab', { name: 'Configuration', exact: true }).click()
    await profile.getByRole('textbox', { name: 'Instructions', exact: true }).waitFor()
    assert.equal(await profile.evaluate((el) => el.scrollWidth > el.clientWidth + 1), false)
    await win.waitForTimeout(220)
    await win.screenshot({ path: path.join(home, 'agents-english-config.png') })
    assert.deepEqual(errors, [])
    console.log('PASS Agent skill and MCP loadout save; screenshots:', home)
  } catch (e) { console.error('Artifacts:', home); try { await (await app?.firstWindow())?.screenshot({ path: path.join(home, 'failure.png') }) } catch {} throw e } finally { await app?.close(); await stub.close() }
}
run().catch(async (e) => { console.error(e); try { const w = (await app?.windows())?.[0]; if (w) await w.screenshot({ path: path.join(home, 'failure.png') }) } catch {} process.exitCode = 1 })
