import { registerMessages } from '../i18n'

registerMessages({
  "startupAppearance.title": { zh: "开屏与图标", en: "Startup and icons" },
  "startupAppearance.description": { zh: "选择内置图片、上传图片或插件方案。", en: "Choose built-in artwork, uploads or plugin presets." },
  "startupAppearance.icon": { zh: "应用图标", en: "App icon" },
  "startupAppearance.splash": { zh: "开屏素材", en: "Startup artwork" },
  "startupAppearance.default": { zh: "默认", en: "Default" },
  "startupAppearance.scene.treeShadow": { zh: "默认 · 树影", en: "Default · Tree shadow" },
  "startupAppearance.scene.classic": { zh: "经典图标", en: "Classic logo" },
  "startupAppearance.sceneHint": { zh: "树影不跟随应用图标；呼吸和旋转只作用于图标类开屏，静止时树影停在一帧。", en: "Tree shadow does not follow the app icon. Breathe and Rotate apply to icon-style startup screens; Still holds the tree shadow on one frame." },
  "startupAppearance.upload": { zh: "上传图片", en: "Upload image" },
  "startupAppearance.show": { zh: "显示开屏", en: "Show startup screen" },
  "startupAppearance.motion": { zh: "加载动画", en: "Loading animation" },
  "startupAppearance.motion.default": { zh: "默认", en: "Default" },
  "startupAppearance.motion.pulse": { zh: "呼吸", en: "Breathe" },
  "startupAppearance.motion.spin": { zh: "旋转", en: "Rotate" },
  "startupAppearance.motion.none": { zh: "静止", en: "Still" },
  "startupAppearance.native": { zh: "同步到 Dock／任务栏", en: "Use in Dock / taskbar" },
  "startupAppearance.nativeScope": { zh: "退出 Forsion 后仍保留", en: "Kept after Forsion quits" },
  "startupAppearance.launcher": { zh: "同步到桌面图标", en: "Use as home screen icon" },
  "startupAppearance.launcherScope": { zh: "仅内置图标", en: "Built-in icons only" },
  "startupAppearance.launcherHint": { zh: "Android 只允许应用在安装包自带的图标之间切换：选内置图标时桌面图标跟着换，上传的图片和插件图标只在应用内显示。切换后，桌面上原来的图标可能需要从应用列表重新添加。", en: "Android only lets an app switch between the icons shipped inside it: built-in icons also change the home screen icon, while uploads and plugin icons are shown inside the app only. After switching, you may need to add the icon to your home screen again from the app list." },
  "startupAppearance.help": { zh: "格式与说明", en: "Formats and details" },
  "startupAppearance.nativeHint": { zh: "应用图标同时写进系统，退出 Forsion 后仍然保留：macOS 上是访达、Dock 和启动台里的图标，Windows 上是开始菜单、桌面和任务栏的快捷方式；应用更新后在下次启动时重新写入。Linux 上只在运行时生效。安装包的图标保持原样。", en: "The app icon is also saved to the system, so it stays after Forsion quits: the icon in Finder, the Dock and Launchpad on macOS, and the Start menu, desktop and taskbar shortcuts on Windows. It is saved again on the first launch after an update. On Linux it applies only while Forsion is running. The installer keeps its original artwork." },
  "startupAppearance.hint": { zh: "支持 PNG、JPEG、SVG、GIF、WebP。可导入不超过 20 MB、6400 万像素（单边不超过 16384 像素）的原图，保存前自动缩小、压缩。支持预览和正方形裁剪。", en: "PNG, JPEG, SVG, GIF or WebP. Import up to 20 MB and 64 megapixels (maximum 16384 pixels per side), with automatic resizing and compression before saving. Preview and square cropping are available." },
  "startupAppearance.behavior": { zh: "图标立即生效；开屏在下次启动时显示。减少动态效果时使用静态图标。", en: "Icons update immediately; startup changes appear on the next launch. Reduced motion uses the still icon." },
  "startupAppearance.plugins": { zh: "插件提供", en: "From plugins" },
  "startupAppearance.builtins": { zh: "内置", en: "Built-in" },
  "startupAppearance.uploaded": { zh: "已上传图片", en: "Uploaded image" },
  "startupAppearance.preview": { zh: "预览开屏", en: "Preview startup" },
  "startupAppearance.reset": { zh: "恢复默认", en: "Restore defaults" },
  "startupAppearance.close": { zh: "关闭预览", en: "Close preview" },
  "startupAppearance.empty": { zh: "安装提供开屏或图标的插件后，可在这里选择。", en: "Install a plugin with startup artwork or icons to find more options here." },
  "startupAppearance.importIcon": { zh: "导入应用图标", en: "Import app icon" },
  "startupAppearance.importSplash": { zh: "导入开屏素材", en: "Import startup artwork" },
  "startupAppearance.framing": { zh: "图片显示方式", en: "Image framing" },
  "startupAppearance.fit": { zh: "完整显示", en: "Fit image" },
  "startupAppearance.crop": { zh: "正方形裁剪", en: "Square crop" },
  "startupAppearance.cropArea": { zh: "裁剪预览，使用方向键移动图片", en: "Crop preview, use arrow keys to move the image" },
  "startupAppearance.zoom": { zh: "缩放", en: "Zoom" },
  "startupAppearance.resetCrop": { zh: "重置裁剪", en: "Reset crop" },
  "startupAppearance.cropHint": { zh: "拖动图片调整位置，滑动缩放；也可用方向键微调。", en: "Drag to reposition and use the slider to zoom. Arrow keys make fine adjustments." },
  "startupAppearance.fitHint": { zh: "保留完整画面和透明区域，图片不会被拉伸。", en: "Keeps the full image and transparency without stretching." },
  "startupAppearance.iconOutput": { zh: "自动缩小并保存为 256 × 256 的圆角应用图标。", en: "Automatically resized to a rounded 256 × 256 app icon." },
  "startupAppearance.splashOutput": { zh: "大图片会自动缩小、压缩，确认后应用。", en: "Large images are automatically resized and compressed before applying." },
  "startupAppearance.animationKept": { zh: "将保留原图动画。", en: "The original animation will be preserved." },
  "startupAppearance.animationStill": { zh: "本次处理将保存为静态图片。", en: "This edit will save a still image." },
  "startupAppearance.cancel": { zh: "取消", en: "Cancel" },
  "startupAppearance.apply": { zh: "确认使用", en: "Apply image" },
  "startupAppearance.saving": { zh: "正在保存…", en: "Saving…" },
  "startupAppearance.error.format": { zh: "不支持此图片格式，请选择 PNG、JPEG、SVG、GIF 或 WebP。HEIC、ICO 请先转换为 PNG。", en: "Unsupported image format. Choose PNG, JPEG, SVG, GIF or WebP. Convert HEIC or ICO files to PNG first." },
  "startupAppearance.error.size": { zh: "原图超过 20 MB，请先缩小后导入。20 MB 以内会自动处理。", en: "The source exceeds 20 MB. Reduce it before importing; smaller files are processed automatically." },
  "startupAppearance.error.dimensions": { zh: "图片超过 6400 万像素或单边 16384 像素，请先缩小后导入。", en: "The image exceeds 64 megapixels or 16384 pixels per side. Reduce its dimensions before importing." },
  "startupAppearance.error.decode": { zh: "无法读取这张图片，文件可能已损坏。请重新导出为 PNG 或 JPEG 后重试。", en: "This image could not be decoded and may be damaged. Export it as PNG or JPEG and try again." },
  "startupAppearance.error.encode": { zh: "图片处理失败，请重新导出为 PNG 或 JPEG 后重试。", en: "Image processing failed. Export it as PNG or JPEG and try again." },
  "startupAppearance.error.save": { zh: "设置保存失败，请检查可用存储后重试。", en: "Settings could not be saved. Check available storage and retry." },
})
