import { beforeEach, afterEach, expect, it } from 'vitest';
import { configureTangu } from '../src/seams/runtime.js';
import { createTanguProfile } from '../src/profiles/index.js';
import { createSqliteHost } from '../src/adapters/standalone/sqliteHost.js';
import { toSqliteDDL } from '../src/core/dialectDDL.js';
import { STANDALONE_SCHEMA } from '../src/db/schemaStandalone.js';
import { runMigration } from '../src/db/migrate.js';
import { query } from '../src/core/db.js';
import { createDelegateTranscript, isDelegateActive } from '../src/services/delegateTranscript.js';
let close: () => void;
beforeEach(async () => {
  const { host, db } = createSqliteHost({ dataDir: 'memory', localToken: 'x', userId: 'u1' });
  close = () => db.close();
  db.exec(toSqliteDDL(STANDALONE_SCHEMA));
  configureTangu({ host, brain: { llm: {} } as any, billing: {} as any, profile: createTanguProfile({ sandboxMode: 'none' }) });
  await runMigration();
  await query('INSERT INTO chat_sessions (id, user_id, app_id, title) VALUES (?, ?, ?, ?)', ['parent', 'u1', 'tangu', 'Main']);
});
afterEach(() => close());
it('persists full child content, reasoning and tools in one assistant row, preserving parent isolation and continuation scope', async () => {
  const transcript = await createDelegateTranscript('child', { userId: 'u1', appId: 'tangu', sessionId: 'parent', agentSlug: 'coordinator', execMode: 'host', cwd: '/tmp/project' } as any, 'Research', 'model', 'Read the evidence', { agentSlug: 'researcher', subAgentGrants: ['manage_schedule'] });
  expect(isDelegateActive('child')).toBe(true);
  const longResult = 'full evidence '.repeat(500) + 'END';
  transcript.token('First observation.');
  transcript.reasoning('Consider the full result.');
  transcript.tool('call-1', 'read_file', '{"path":"evidence.md"}', longResult, false);
  await transcript.save();
  transcript.token(' Final conclusion.');
  await transcript.finish();
  expect(isDelegateActive('child')).toBe(false);
  const rows = await query<any[]>('SELECT * FROM chat_messages WHERE session_id = ? ORDER BY timestamp', ['child']);
  expect(rows).toHaveLength(2);
  const answer = rows.find((m) => m.role === 'model')!;
  expect(answer.content).toBe('First observation. Final conclusion.');
  expect(answer.reasoning).toBe('Consider the full result.');
  const parse = (v: any) => typeof v === 'string' ? JSON.parse(v) : v;
  expect(parse(answer.tool_results)[0].content).toBe(longResult);
  expect(parse(answer.tool_calls)[0].ui_content_offset).toBe('First observation.'.length);
  const [session] = await query<any[]>('SELECT * FROM chat_sessions WHERE id = ?', ['child']);
  expect(session.kind).toBe('delegate');
  expect(session.parent_session_id).toBe('parent');
  expect(parse(session.agent_config)).toMatchObject({ cwd: '/tmp/project', agentSlug: 'researcher', delegatedFrom: 'parent', delegatedBy: 'coordinator', subAgentGrants: ['manage_schedule'] });
  expect(await query('SELECT * FROM chat_messages WHERE session_id = ?', ['parent'])).toEqual([]);
});
